"""
Revision ID: 52459363f20d
Revises: 688272c89cf2
Create Date: 2025-10-14 15:55:17.601832

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '52459363f20d'
down_revision = '688272c89cf2'
branch_labels = None
depends_on = None
from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create tables explicitly (safe for fresh DBs). Use IF NOT EXISTS so we don't error on existing DB.
    op.execute("""
    CREATE TABLE IF NOT EXISTS mesas (
        id INTEGER PRIMARY KEY,
        nombre VARCHAR,
        qr_code VARCHAR
    );
    """)

    op.execute("""
    CREATE TABLE IF NOT EXISTS usuarios (
        id INTEGER PRIMARY KEY,
        nick VARCHAR,
        puntos INTEGER DEFAULT 0,
        nivel VARCHAR DEFAULT 'bronce',
        last_active DATETIME,
        is_silenced BOOLEAN DEFAULT 0,
        mesa_id INTEGER
    );
    """)

    op.execute("""
    CREATE TABLE IF NOT EXISTS canciones (
        id INTEGER PRIMARY KEY,
        youtube_id VARCHAR,
        titulo VARCHAR,
        duracion_seconds INTEGER DEFAULT 0,
        estado VARCHAR DEFAULT 'pendiente',
        started_at DATETIME,
        orden_manual INTEGER,
        created_at DATETIME,
        finished_at DATETIME,
        usuario_id INTEGER
    );
    """)

    op.execute("""
    CREATE TABLE IF NOT EXISTS productos (
        id INTEGER PRIMARY KEY,
        nombre VARCHAR UNIQUE,
        categoria VARCHAR,
        valor NUMERIC(10,2),
        stock INTEGER DEFAULT 0,
        is_active BOOLEAN DEFAULT 1
    );
    """)

    op.execute("""
    CREATE TABLE IF NOT EXISTS consumos (
        id INTEGER PRIMARY KEY,
        cantidad INTEGER DEFAULT 1,
        valor_total NUMERIC(10,2),
        created_at DATETIME,
        producto_id INTEGER,
        usuario_id INTEGER
    );
    """)

    op.execute("""
    CREATE TABLE IF NOT EXISTS banned_nicks (
        id INTEGER PRIMARY KEY,
        nick VARCHAR UNIQUE,
        banned_at DATETIME
    );
    """)

    op.execute("""
    CREATE TABLE IF NOT EXISTS admin_logs (
        id INTEGER PRIMARY KEY,
        timestamp DATETIME,
        action VARCHAR,
        details VARCHAR
    );
    """)

    op.execute("""
    CREATE TABLE IF NOT EXISTS admin_api_keys (
        id INTEGER PRIMARY KEY,
        key VARCHAR UNIQUE NOT NULL,
        description VARCHAR,
        is_active BOOLEAN DEFAULT 1,
        created_at DATETIME,
        last_used DATETIME
    );
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For safety, do not drop tables automatically on downgrade in this migration.
    pass
    # ### end Alembic commands ###
