"""
Revision ID: 688272c89cf2
Revises: 
Create Date: 2025-10-14 15:51:52.503538

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '688272c89cf2'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
